### ISSUE TITLE
There was a problem sending login to: https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin

### ISSUE THREAD

**Issue by weghorst** [zephyrus/homebridge-melcloud2#1]
[Melcloud] There was a problem sending login to: https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin
[7/25/2020, 07:17:28] [Melcloud] Error: getaddrinfo EAI_AGAIN app.melcloud.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'app.melcloud.com'
}

I am getting this error for a week now. It was working perfectly before...

**Comment by zephyrus** [comment]
@weghorst where are you living? maybe machine running service do not have access to melcloud resources?

**Comment by weghorst** [comment]
It's working again ... probably some MelCloud issue

**Comment by sacapo** [comment]
Hi from Spain

I am getting same issue, the only way to get it is with:
https://app.melcloud.com

thanks

**Comment by sacapo** [comment]
never mind!!! Working like a charm1!!!  thanks
